blueprint:
  name: Schalte laut Zeitplan
  description: Schalte basierend auf einem Zeitplan
  domain: automation
  input:
    time_on:
      name: Uhrzeit an
      selector:
        time:
    time_off:
      name: Uhrzeit aus
      selector:
        time:
    target:
      name: Ziel
      selector:
        target:
trigger:
  - platform: time
    at: !input time_on
  - platform: time
    at: !input time_off
  - platform: homeassistant
    event: start
condition: []
action:
  - if:
      - condition: time
        after: !input time_on
        before: !input time_off
    then:
      - service: homeassistant.turn_on
        data: {}
        target: !input target
    else:
      - service: homeassistant.turn_off
        data: {}
        target: !input target
