blueprint:
  name: Schalte laut Zeitplan
  description: Schalte basierend auf einem Zeitplan
  domain: automation
  input:
    time_on:
      name: Uhrzeit an
      selector:
        time:
    time_off:
      name: Uhrzeit aus
      selector:
        time:
    target:
      name: Ziel
      selector:
        target:
trigger:
  - platform: time
    id: "on"
    at: !input time_on
  - platform: time
    id: "off"
    at: !input time_off
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
        sequence:
          - service: homeassistant.turn_on
            data: {}
            target: !input target
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - service: homeassistant.turn_off
            data: {}
            target: !input target
